config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'feed',:to=>'home#feed'

  get 'en', :to=> 'home#index',:defaults => { :locale => 'en'}
  get 'ko', :to=> 'home#index',:defaults => { :locale => 'ko'}
  get 'ch', :to=> 'home#index',:defaults => { :locale => 'zh-CN'}

  #faqs
  resources :faqs, only:[:index,:show]

  #contacts
  resources :contacts, only:[:index,:create, :show]
  get "/contacts/new", to: redirect("/contacts")

  #intro
  get 'intro', :to=>'intro#company', as: 'intro'
  get 'intro/service', :to=>'intro#service', as: 'intro_service'
  get 'intro/program', :to=>'intro#program', as: 'intro_program'

  resources :programs
  resources :accounts
  resources :accounts_products
  resources :accounts_product_categories
  resources :orders
  resources :reports
  resources :notices
  resources :users, :sitemap

  get "product_categories/:id",
      to: redirect(status: 301) { |params, _|
        "/orders?product_category=#{params[:id]}"
      },
      as: :product_category

  get "products/:id", to: redirect(status: 301) { |params, _req|
    "/orders?product=#{params[:id]}"
  }


  get 'install', :to=>'programs#install', as: 'program_install'

  devise_for :admins, :controllers => { :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}
  devise_for :users, :controllers => {:omniauth_callbacks=>'users/omniauth_callbacks', :sessions => "users/sessions",:registrations => "users/registrations",:passwords => "users/passwords"}, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  # 관리자
  namespace :admin do
    root to: 'home#index'

    resources :contacts
    resources :users
    resources :product_categories
    resources :products
    resources :orders
    resources :notices
    resources :faq_categories
    resources :faqs
  end
end

app/models/account.rb
class Account < ApplicationRecord
  after_initialize :default_values
  belongs_to :account_category
  belongs_to :user, counter_cache: true
  has_many :accounts_orders, dependent: :destroy
  has_many :accounts_products, dependent: :destroy
  has_many :orders, :through => :accounts_orders
  has_many :products, :through => :accounts_products
  private

  def default_values
    self.transaction_date ||= Date.today
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable, :timeoutable, :rememberable

  has_one :admin_picture, dependent: :destroy
  has_one :role_admin
  has_one :role, through: :role_admin
  has_many :admin_login_log, dependent: :destroy
  accepts_nested_attributes_for :admin_picture, allow_destroy: true

  validates_length_of :email, within: 4..40
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_uniqueness_of :email
  validates_length_of :name, within: 1..60

  def role?(role)
    unless self.role.present?
      return false
    end

    if self.role.role==role.to_s
      return true
    else
      return false
    end
  end

  def timeout_in
    1.day
  end

  private

  def email_required?
    false
  end

  def timeout_in
    1.day
  end
end

app/models/admin_home.rb
class AdminHome < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :title, :email, :name
  validates :contact_content, :presence => true
  belongs_to :user, counter_cache: true

  has_one :contact_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :contact
  validates :contact_content, :presence => true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  accepts_nested_attributes_for :contact_content, :allow_destroy => true, :update_only => true

  def contact_content
    super || build_contact_content
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
  has_rich_text :content
  validates_presence_of :title
  translates :title
  belongs_to :faq_category, counter_cache: true
end

app/models/faq_category.rb
class FaqCategory < ApplicationRecord
  validates_presence_of :title
  translates :title
  has_many :faq, dependent: :destroy
end

app/models/faq_content.rb
class FaqContent < ApplicationRecord
  validates_presence_of :content
  translates :content
  belongs_to :faq, :foreign_key => :id, inverse_of: :faq_content
end

app/models/home.rb
class Home < User
end

app/models/notice.rb
class Notice < ApplicationRecord
  is_impressionable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content
  validates_presence_of :title
  has_one :notice_picture, dependent: :destroy
  accepts_nested_attributes_for :notice_picture, :allow_destroy => true
end

app/models/order.rb
class Order < ApplicationRecord
  after_initialize :default_values

  validates_presence_of :user_id,:price,:discount,:payment
  validates :title,
            presence: true,
            length: {
              maximum: 60,
              too_long: "제목은 60자 이내여야 합니다."
            }
  belongs_to :user, counter_cache: true
  has_many :accounts_orders, dependent: :destroy
  has_many :orders_products, dependent: :destroy
  has_many :products, :through => :orders_products
  has_many :accounts, :through => :accounts_orders
  has_one :order_content, dependent: :destroy

  accepts_nested_attributes_for :order_content, allow_destroy: true, reject_if: proc { |attrs| attrs['content'].blank? }

  private

  def default_values
    self.transaction_date ||= Date.today
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :title
  belongs_to :product_category, counter_cache: true
  has_many :orders, :through => :orders_products
  has_one :product_picture, dependent: :destroy
  has_one :product_content, dependent: :destroy
  accepts_nested_attributes_for :product_picture, :allow_destroy => true
end

app/models/program.rb
class Program < ActiveRecord::Base
  is_impressionable
  validates_presence_of :title
  validates_length_of :title, :minimum => 3, :maximum => 60, :allow_blank => true
  has_many :program_categories_programs
  has_many :program_categories, :through => :program_categories_programs
  has_many :program_links
  has_many :program_pictures, dependent: :destroy
  has_one :program_content, :foreign_key => :id, :dependent => :destroy
  accepts_nested_attributes_for :program_content, :allow_destroy => true
  accepts_nested_attributes_for :program_pictures, :allow_destroy => true
end

app/models/program_link.rb
class ProgramLink< ActiveRecord::Base
  validates_presence_of :program_id, :program_link_category_id
  validates :program_id, :numericality => { :only_integer => true }
  belongs_to :program_link_category
  belongs_to :program
end

app/models/propose.rb
class Propose < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :user,:autosave=>true
end

app/models/report.rb
class Report < ActiveRecord::Base
  acts_as_votable
  is_impressionable
  validates_presence_of :title
  belongs_to :user, counter_cache: true
  belongs_to :report_category, counter_cache: true
  has_one :report_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :report
  accepts_nested_attributes_for :report_content, :allow_destroy => true, :update_only => true

  def report_content
    super || build_report_content
  end
end

app/models/role.rb
class Role < ApplicationRecord
  validates_presence_of :title
  has_one :role_admin, dependent: :destroy
  has_one :admin, through: :role_admin, dependent: :destroy
end

app/models/role_admin.rb
class RoleAdmin < ApplicationRecord
  belongs_to :role
  belongs_to :admin
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true
  belongs_to :user, :autosave=>true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag, :counter_cache => true
end

app/models/user.rb
class User < ActiveRecord::Base
  include OmniauthAttributesConcern
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:kakao, :naver, :facebook, :twitter, :apple, :google_oauth2]

  validates_presence_of :name, :email, :on => :create
  validates_length_of :email, :within => 4..255
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_length_of :password, :within => 4..255, :allow_blank => true
  has_many :user_authorizations

  def self.create_from_omniauth(params)
    self.__send__(params.provider, params)
  end
end

app/views/admins/_aside.html.erb
<aside class="col-12 col-lg-5 col-xl-4 col-xxl-3">
  <%= render :partial => 'admin/admins/profile' %>
  <%= render :partial => 'admin/admins/list' %>
  <%= paginate @admins %>
  <%=link_to t(:add),new_admin_admin_path,class: 'btn btn-primary' %>
</aside>

app/views/admins/_content.html.erb
<article class="card">
  <div class="card-header">
    <h3><%=t(:admin_info) %></h3>
    <%= link_to edit_admin_admin_path(@admin), class: 'more2' do %>
      <i class="material-icons">edit</i>
    <% end %>
    <%= link_to admin_admin_path(@admin), class: 'more' do %>
      <i class="material-icons">delete</i>
    <% end %>
  </div>
  <div class="card-body">
      <div class="row">
        <div class="col-12 col-md-6 col-xl-4 form-group">
          <label><%=t(:name, scope: [:activerecord, :attributes, :admin]) %></label>
          <p>
            <%= @admin.name %>
          </p>
        </div>
        <% if @admin.attributes['card_no'] %>
          <div class="col-12 col-md-6 col-xl-4 form-group">
            <label><%=t(:card_no, scope: [:activerecord, :attributes, :admin]) %></label>
            <p><%= @admin.card_no %></p>
          </div>
        <% end %>
        <div class="col-12 col-md-6 col-xl-4 form-group">
          <label><%=t(:phone, scope: [:activerecord, :attributes, :admin]) %></label>
          <p><%= @admin.phone %></p>
        </div>

        <div class="col-12 col-md-6 col-xl-4 form-group">
          <label><%=t(:birthday, scope: [:activerecord, :attributes, :admin]) %></label>

          <p></p>
        </div>

        <div class="col-12 col-md-6 col-xl-4 form-group">
          <label><%=t(:registration_date, scope: [:activerecord, :attributes, :admin]) %></label>
          <p><%=@admin.registration_date %></p>
        </div>
      </div>
  </div>
</article>

app/views/admins/_form.html.erb
<%= form_with(model: [:admin, admin], local: true) do |form| %>
  <div class="card">
    <div class="card-body">
      <div class="form-row">
        <div class="form-group col-12 col-md-6 col-xl-4">
          <%= form.label :email %>
          <%= form.text_field :email, :class => 'form-control', :required => 'required' %>
        </div>
        <div class="form-group col-12 col-md-6 col-xl-4">
          <%= form.label :password %>
          <%= form.password_field :password, :class => 'form-control', :required => 'required' %>
        </div>
        <div class="form-group col-12">
          <%= form.label :role %>
          <%= form.fields_for :roles_admin do |ar| %>
            <%= ar.select :role_id, options_from_collection_for_select(Role.where(:enable=>true).all, 'id', 'title'),{:id=>3},{:class=>"form-control"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <div class="form-row">
        <div class="col-12 col-md-6 col-xl-4 form-group">
          <%= form.label :name %>
          <%= form.text_field :name, :class => 'form-control', :required => 'required' %>
        </div>
        <div class="col-12 col-md-6 col-xl-4 form-group">
          <%= form.label :phone %>
          <%= form.text_field :phone, :class => 'form-control' %>
        </div>
        <div class="col-12 col-md-6 col-xl-4 form-group">
          <%= form.label :birthday %>
          <%= form.date_field :birthday, :class => 'form-control' %>
        </div>
        <div class="col-12 col-md-6 col-xl-4 form-group">
          <%= form.label :gender %>
          <div class="form-row">
            <div class="col-12">
              <div class="form-check form-check-inline">
                <%= label_tag 'male', { :class => 'form-check-label', :for => nil } do %>
                  <%= form.radio_button :gender, 1, { :class => 'form-check-input' } %><%= t(:male) %>
                <% end %>
              </div>
              <div class="form-check form-check-inline">
                <%= label_tag 'female', { :class => 'form-check-label', :for => nil } do %>
                  <%= form.radio_button :gender, 0, { :class => 'form-check-input' } %><%= t(:female) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-6 col-xl-4 form-group">
          <%= label_tag 'gg' %>
          <div class="form-row">
            <div class="col-12">
              <div class="form-check form-check-inline">
                <%= form.label :is_fc, :class => 'form-check-label' do %>
                  <%= form.check_box :is_fc, { :class => 'form-check-input' },1,nil %>
                  <%= t(:is_fc) %>
                <% end %>
              </div>
              <div class="form-check form-check-inline">
                <%= form.label :is_trainer, :class => 'form-check-label' do %>
                  <%= form.check_box :is_trainer, { :class => 'form-check-input' },1,nil %>
                  <%= t(:is_trainer) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-6 col-xl-4 form-group"<% unless @admin.is_trainer %> style="display:none"<% end %>>
          <%= form.label :commission_rate %>
          <%= form.number_field :commission_rate, :class => 'form-control' %>
        </div>

        <div class="col-12 col-md-6 col-xl-4 form-group">
          <%= form.label :registration_date %>
          <%= form.date_field :registration_date, :class => 'form-control', :required => 'required' %>
        </div>
      </div>
    </div>
  </div>
  <%= render :partial => 'form_content', locals: {f: form} %>
  <%= form.submit :class => 'btn btn-primary btn-block btn-lg' %>
<% end %>

app/views/admins/_form_content.html.erb
<%= f.fields_for :admin_contents do |content| %>
<div class="card">
  <div class="card-header" style="cursor: pointer;">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item"><a class="nav-link" href="#"><%= t(:content, scope: [:activerecord, :attributes, :admin_content]) %></a></li>
    </ul>
    <div class="float-right buttons">
      <i class="material-icons">keyboard_arrow_down</i>
    </div>
  </div>
  <div class="card-body" style="display:none">
    <div class="card-block">
      <div class="row">
          <div class="col-12 form-group">
            <%= content.label :content %>
            <%= content.text_area :content, :id => "sl_content", :class => 'form-control' %>
          </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admins/_list.html.erb
<article id="employee-list" class="row">
  <input type="hidden" id="user_list_count" value="<%=@admin_counts %>">
  <div class="col-12">
    <table class="table table-striped table-hover">
      <colgroup>
        <col class="d-none d-lg-table-cell" />
        <col />
        <col />
      </colgroup>
      <thead class="thead-default">
      <tr>
        <th class="d-none d-lg-table-cell di-title"><%=t(:increment_number) %></th>
        <th><%=t(:user_name) %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% unless @admins.empty? %>
        <% @admins.each_with_index do |admin, index| %>
          <tr<% if @admin.id == admin.id %> class="table-primary"<% end %>>
            <td class="d-none d-lg-table-cell user-index">
              <%
                if params[:page].present?
                  mm=(params[:page].to_i-1)
                else
                  mm=0
                end
              %>
              <%=@admin_count-(params[:per_page].to_i*mm)-index %>
            </td>
            <td>
              <div style="display:block;width:100px;white-space:nowrap;text-overflow:ellipsis">
                <%=link_to admin.name,admin_admin_path(admin) %>
              </div>
            </td>
            <td>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4"><%=t(:no_data) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</article>

app/views/admins/_nav.html.erb
<div class="row">
  <nav class="col-12 sub-nav">
    <ul class="nav nav-pills">
      <li class="nav-item"><%= link_to t(:default_info),'', class: get_nav_active_class(['index','show','edit']) %></li>
      <li class="nav-item"><%= link_to t(:my_user),'', class: get_nav_active_class(['users']) %></li>
      <li class="nav-item"><%= link_to t(:memo),'', class: get_nav_active_class(['memo']) %></li>
    </ul>
  </nav>
</div>

app/views/admins/_profile.html.erb
<article class="row admin-info">
  <h3 class="col-12"><% t(:selected_admin_info) %></h3>
  <div class="col-12 col-sm-6">
    <% if @admin.admin_picture.present? %>
      <a href="<%=@admin.admin_picture.picture.url %>" class="simple_image">
        <%=image_tag @admin.admin_picture.picture.medium_thumb.url,:width=>"100%",:height=>"100%",:id=>"profile_photo" %>
      </a>
    <% else %>
      <%=image_tag 'bg_photo_none.gif',:width=>"100%",:height=>"100%",:id=>"profile_photo" %>
    <% end %>
  </div>
  <div class="col-12 col-sm-6">
    <ul>
      <% unless @admin.present? %>
        <li><span class="btn btn-sm btn-light btn-block btn-outline-info">-</span>
        <li><span class="btn btn-sm btn-light btn-block btn-outline-info">-</span>
      <% else %>
        <li>
        <span class="btn btn-sm btn-light btn-block btn-outline-info">
          <% if @admin.name.present? %>
          <%= @admin.name %>
          <% else %>
            -
          <% end  %>
        </span>
        </li>
        <li>
          <% if true %>
        <span class="btn btn-sm btn-light btn-block btn-outline-info">
          <% if @admin.phone.present? %>
          <%= @admin.phone %>
          <% else  %>
          <%=t(:not_inserted) %>
          <% end  %>
        </span>
          <% else %>
        <span class="btn btn-sm btn-light btn-block btn-outline-info">
          card-no
				</span>
          <% end %>
        </li>
        <li>
          <%=link_to t(:photo_shoot),new_admin_admin_picture_path(:admin_id=>@admin),{:target => '_blank', :class => 'btn btn-sm btn-outline-secondary btn-block btn-popup'} %>
        </li>
        <li>
          <span id="photo_load" class="btn btn-sm btn-outline-secondary btn-block"><%=t(:select_photo) %></span>
          <%= form_with(model: [:admin,AdminPicture.new], local: true, html: {:id => 'form_photo', :style => 'display:none'}) do |form| %>
            <input type="hidden" name="admin_id" value="<%=@admin.id %>">
            <input type="file" name="photo[]" accept="image/*" capture="">
            <%= form.submit t(:upload_photo), :class => 'btn btn-sm btn-secondary btn-block' %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</article>

app/views/admins/edit.html.erb
<section id="edit-user" class="container">
  <div class="row">
    <h2 class="col-12"><%= t(:edit_admin) %></h2>
  </div>
  <div class="row">
    <%= render :partial => 'aside' %>
    <div class="col-12 col-lg-7 col-xl-8 col-xxl-9 user_sub">
      <section class="row">
        <div class="col-12">
          <h2 class="di-title"><%= t(:user_detail) %></h2>
          <% if @admin.nil? %>
            <%= render :partial => 'not_found' %>
          <% else %>
            <%= render :partial => 'nav' %>
            <%= render 'form', admin: @admin %>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/admins/index.html.erb
<div id="admins" class="container">
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals => {  :notice => notice, :alert => alert } %>
  </div>
  <div class="row">
    <%= render :partial => 'aside' %>
    <div class="col-12 col-lg-7 col-xl-8 col-xxl-9 user_sub">
      <section class="row user-content-section">
        <div class="col-12">
          <h2 class="di-title"><%= t(:employee_detail_info) %></h2>
          <% if @admin.nil? %>
            <%= render :partial => 'not_found' %>
          <% else %>
            <%= render :partial => 'nav' %>
            <%= render :partial => 'content' %>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<section id="new-admin" class="container">
  <div class="row">
    <h2 class="col-12"><%= t(:new_admin) %></h2>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', admin: @admin %>
    </div>
  </div>
</section>

app/views/admins/show.html.erb
<section id="show-admin" class="container">
  <div class="row">
    <h2 class="col-12 di-title"><%= t(:show_admin) %></h2>
  </div>
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals => { :notice => notice, :alert => alert } %>
  </div>
  <div class="row">
    <%= render :partial => 'aside' %>
    <div class="col-12 col-lg-7 col-xl-8 col-xxl-9 user_sub">
      <section class="row user-content-section">
        <div class="col-12">
          <h2 class="di-title"><%= t(:admin_detail) %></h2>
          <% if @admin.nil? %>
            <%= render :partial => 'not_found' %>
          <% else %>
            <%= render :partial => 'nav' %>
            <%= render :partial => 'content' %>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/layouts/admin/_aside.html.erb
<aside id="main-menu" class="col-12 col-md-3 col-lg-2 col-xl-1">
  <h1 class="col-12"><%= link_to t(:service_name), admin_root_path %></h1>
  <nav>
    <ul class="nav">

      <li class="nav-item
            <% if ['admin/products','admin/product_categories'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_products_path, :class => "nav-link" do %>
          <i class="material-icons">shopping_cart</i><span><%= t(:product, scope: [:activerecord, :models]) %></span>
        <% end %>
      </li>
      <li class="nav-item
            <% if ['admin/orders'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_orders_path, :class => "nav-link" do %>
          <i class="material-icons">shopping_cart</i><span><%= t(:order, scope: [:activerecord, :models]) %></span>
        <% end %>
      </li>
      <li class="nav-item
            <% if ['admin/users','admin/companies','admin/user_point_logs'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_users_path, :class => "nav-link" do %>
          <i class="material-icons">person</i><span><%= t(:user, scope: [:activerecord, :models]) %></span>
        <% end %>
      </li>

      <li class="nav-item
            <% if ['admin/notices','admin/faq_categories','admin/contacts','admin/faqs','admin/reviews','admin/reservations','admin/questions','admin/answers'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_notices_path, :class => "nav-link" do %>
          <i class="material-icons">people</i><span><%= t(:menu_community) %></span>
        <% end %>
      </li>

    </ul>
  </nav>
</aside>

app/views/layouts/admin/_footer.html.erb
<footer>
  <div class="container">
    <ul class="row">
      <li class="col-6">
      <address >
        &nbsp;&nbsp; Copyright ⓒ. 2022, <%=t(:company) %>. All Right Reserved.
      </address>
      </li>
  <li class="col-6">
    <%= link_to '#', { class: 'dropdown-toggle d-flex align-items-center gap-2',
                       role: "button",
                       'data-bs-toggle': "dropdown",
                       'aria-expanded': "false" } do %>
      <span><%=t(:theme) %></span>
      <span class="current-theme-icon"></span>
    <% end %>
    <ul class="dropdown-menu">
      <li>
        <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="light">
          <span class="icon">☀️</span>
          <%=t(:light) %>
        </button>
      </li>
      <li>
        <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="dark">
          <span class="icon">🌙</span>
          <%=t(:dark) %>
        </button>
      </li>
      <li>
        <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="auto">
          <span class="icon">🌓</span>
          <%=t(:auto) %>
        </button>
      </li>
    </ul>
  </li>
    </ul>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="row">
  <div class="col-12">
    <% if ['admin/ads','admin/biddings','admin/accepted_biddings'].include?(params[:controller]) %>
    <%= render 'admin/ads/nav' %>
    <% end %>
    <% if ['admin/blogs','admin/blog_categories'].include?(params[:controller]) %>
      <%= render 'admin/blogs/nav' %>
    <% end %>
    <% if ['admin/products','admin/product_categories'].include?(params[:controller]) %>
      <%= render 'admin/products/nav' %>
    <% end %>
    <% if ['admin/orders','admin/payments'].include?(params[:controller]) %>
      <%= render 'admin/orders/nav' %>
    <% end %>
    <% if ['admin/notices','admin/contacts','admin/questions','admin/answers','admin/faq_categories','admin/faqs','admin/reviews','admin/reservations'].include?(params[:controller]) %>
      <%= render 'admin/notices/nav' %>
    <% end %>
    <% if ['admin/slides','admin/settings'].include?(params[:controller]) %>
      <%= render 'admin/settings/nav' %>
    <% end %>
    <% if ['admin/users','admin/companies','admin/user_point_logs'].include?(params[:controller]) %>
      <%= render 'admin/users/nav' %>
    <% end %>
    <% if ['admin/simulations','admin/simulation_pictures','admin/simulation_blueprints','admin/simulation_materials','admin/user_simulation_materials','admin/simulation_categories'].include?(params[:controller]) %>
      <%= render 'admin/simulations/nav' %>
    <% end %>
    <% if ['admin/admins','admin/addresses','admin/specialities','admin/speciality_categories','admin/materials','admin/sizes','admin/address_levels','admin/charge_points'].include?(params[:controller]) %>
      <%= render 'admin/admins/nav' %>
    <% end %>
    <ul id="top-menu">
      <% if admin_signed_in? %>
        <li id="admin-info">
            <% if current_admin.admin_picture.present? %>
              <%= image_tag(current_admin.admin_picture.picture.small_thumb.url, { :height => 50, :width => 50 }) %>
            <% end %>
            <span class="text-dark"><%= current_admin.name %></span>
        </li>
        <li>
          <%= link_to destroy_admin_session_path, :id => "p_logout", :method => :delete do %>
            <i class="material-icons" style="font-size:35px;vertical-align:middle">highlight_off</i><span><%= t(:logout) %></span>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_admin_session_path do %>
            <i class="material-icons">login</i><span><%= t(:login) %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/admin/_login_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1><%= link_to root_path do %>
            <span class="logo"><%= t(:service_name) %></span>
          <% end %>
        </h1>
      </div>
    </div>
  </div>
</header>

app/views/layouts/admin/popup.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <%= yield %>
  </div>
</div>