config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'feed',:to=>'home#feed'

  get 'en', :to=> 'home#index',:defaults => { :locale => 'en'}
  get 'ko', :to=> 'home#index',:defaults => { :locale => 'ko'}
  get 'ch', :to=> 'home#index',:defaults => { :locale => 'zh-CN'}

  #faqs
  resources :faqs, only:[:index,:show]

  #contacts
  resources :contacts, only:[:index,:create, :show]
  get "/contacts/new", to: redirect("/contacts")

  #intro
  get 'intro', :to=>'intro#company', as: 'intro'
  get 'intro/service', :to=>'intro#service', as: 'intro_service'
  get 'intro/program', :to=>'intro#program', as: 'intro_program'

  resources :programs
  resources :accounts
  resources :accounts_products
  resources :accounts_product_categories
  resources :orders
  resources :reports
  resources :notices
  resources :users, :sitemap

  get "product_categories/:id",
      to: redirect(status: 301) { |params, _|
        "/orders?product_category=#{params[:id]}"
      },
      as: :product_category

  get "products/:id", to: redirect(status: 301) { |params, _req|
    "/orders?product=#{params[:id]}"
  }


  get 'install', :to=>'programs#install', as: 'program_install'

  devise_for :admins, :controllers => { :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}
  devise_for :users, :controllers => {:omniauth_callbacks=>'users/omniauth_callbacks', :sessions => "users/sessions",:registrations => "users/registrations",:passwords => "users/passwords"}, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  # 관리자
  namespace :admin do
    root to: 'home#index'

    resources :contacts
    resources :users
    resources :product_categories
    resources :products
    resources :orders
    resources :notices
    resources :faq_categories
    resources :faqs
  end
end

app/models/order.rb
class Order < ApplicationRecord
  after_initialize :default_values

  validates_presence_of :user_id,:price,:discount,:payment
  validates :title,
            presence: true,
            length: {
              maximum: 60,
              too_long: "제목은 60자 이내여야 합니다."
            }
  belongs_to :user, counter_cache: true
  has_many :accounts_orders, dependent: :destroy
  has_many :orders_products, dependent: :destroy
  has_many :products, :through => :orders_products
  has_many :accounts, :through => :accounts_orders
  has_one :order_content, dependent: :destroy

  accepts_nested_attributes_for :order_content, allow_destroy: true, reject_if: proc { |attrs| attrs['content'].blank? }

  private

  def default_values
    self.transaction_date ||= Date.today
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @order_count = Order.count
    @orders = Order.page(params[:page]).per(params[:per_page]).order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/complete
  def new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to new_admin_order_path, notice: t(:order, scope: [:activerecord, :models])+t(:message_success_update) }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def calculate_account(s, payment_method)
    a = { total_price: 0 }
    if s.empty?
      return a
    end

    s.each do |ss|
      pp = ss.price * ss.quantity

      a[:total_price] += pp
    end

    return a
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:user_id, :transaction_date, :price, :discount, :payment, order_products_attributes: [:product_id, :price, :quantity]).merge(branch_id: session[:branch_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_product, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_controller_name, only: [:new, :create, :index, :show]

  # GET /orders
  # GET /orders.json
  def index
    condition={enable: true}

    if params[:product].present?
      condition[:id]=params[:product]
      @product = Product.where(condition).first
    else
      if params[:product_category].present?
        condition[:product_category_id]=params[:product_category]
        @products = Product.where(condition)
      else
        @product_categories = ProductCategory.where(condition)
      end
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_order_content
  end

  # GET /orders/1/edit
  def edit
    @order.build_order_content unless @order.order_content
  end

  # POST /orders
  # POST /orders.json
  def create
    if Rails.env.production?
      unless verify_turnstile
        flash.now[:alert] = "로봇 차단됨"
        render :new and return
      end
    end

    # 주문 자체 파라미터 추출(클라이언트가 보낸 user_id는 사용하지 않음)
    order_attrs = order_params.to_h.deep_symbolize_keys.except(:user_id)
    product_ids = order_attrs.delete(:product_ids)

    ActiveRecord::Base.transaction do
      # 로그인한 경우: 폼의 name/email은 무시하고 현재 사용자에 연결
      if user_signed_in?
        user = current_user
      else


        # 비로그인: 폼에서 넘어온 고객 정보만 안전하게 추출
        customer_params = params.require(:order).permit(:name, :email)
        name  = customer_params[:name].to_s.strip
        email = customer_params[:email].to_s.strip.downcase

        if email.blank?
          @order = Order.new(order_attrs)
          @order.errors.add(:base, "이메일은 필수입니다.")
          return render :new, status: :unprocessable_entity
        end

        # 이메일 기준으로 사용자 찾거나 생성
        user = User.find_or_initialize_by(email: email)
        if user.new_record?
          user.name        = name
          user.password    = SecureRandom.base64(12)
          user.save!
        else
          user.update!(name: name) if user.name.blank? && name.present?
        end
      end

      # 4) 주문 생성 + user 연결
      @order = Order.new(order_attrs)
      @order.user = user

      count = Array(product_ids).size

      @order.title =
        if count <= 1
          @product.title
        else
          "#{@product.title} 외 #{count - 1}개 상품"
        end


      Array(product_ids).each do |pid|
        product = Product.find(pid)

        @order.orders_products.build(
          product: product,
          price: product.price
        )
      end

      if @order.save
        redirect_to @order, notice: '주문이 생성되었습니다.'
      else
        render :new, status: :unprocessable_entity
      end


    rescue ActiveRecord::RecordInvalid => e
      @order ||= Order.new(order_attrs)
      @order.errors.add(:base, e.record.errors.full_messages.to_sentence)
      render :new, status: :unprocessable_entity
    end
  end



  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    # 주의: user_id는 서버에서만 설정합니다(스푸핑 방지).
    params.require(:order).permit(
      :user_id, :transaction_date, :price, :discount, :payment, product_ids: [], order_content_attributes: [:id, :content]
    )
  end

  def set_product
    product_id =
      params[:product].presence ||
      Array(params.dig(:order, :product_ids)).first

    @product = Product.find(product_id)
  rescue ActiveRecord::RecordNotFound, ArgumentError
    redirect_to products_path, alert: "제품을 찾을 수 없습니다."
  end

  def set_controller_name
    @controller_name = t(:menu_order)
  end
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <h2><%= pluralize(order.errors.count, "개의 문제") %>로 진행할 수 없습니다.</h2>
      <ul>
        <% order.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, :class => 'form-control', :required => 'required' %>
      </div>
    <div class="form-group">
      <%= form.label :popup %>
      <%= form.check_box :popup %>
    </div>
    <div class="form-group">
      <%= form.label :enable %>
      <%= form.check_box :enable %>
    </div>
  </div>
  <div class="form-group actions">
    <%= form.submit :class => "btn btn-primary btn-block btn-lg" %>
  </div>
<% end %>

app/views/admin/orders/_nav.html.erb
<%
    a_class = 'nav-link'
    b_class = 'nav-link'

    if params[:controller] == 'admin/orders'
      a_class += ' active'
    end


  %>
  <div class="col-12">
    <nav class="sub-nav">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to t(:order, scope: [:activerecord, :models]), admin_orders_path, { :class => a_class } %></li>
      </ul>
    </nav>
  </div>

app/views/admin/orders/edit.html.erb
<section id="edit-order" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:edit_order) %></h2>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', order: @order %>
    </div>
  </div>
</section>

app/views/admin/orders/index.html.erb
<div class="col-12">
  <h2 class="float-start d-none d-lg-block"><%= t(:order,scope: [:activerecord,:models]) %></h2>
  <div class="float-end">
    <p class="summary text-end">
          <span id="list_count" style="display:none"><%=@order_count %></span>
          <%=raw t(:there_are_n_orders,count: @order_count) %>
        </p>
      </div>
    </div>
    <article class="col-12">
      <table id="prepare_list" class="table table-striped table-hover">
        <colgroup>
          <col style="width:120px">
          <col>
          <col style="width:100px">
          <col style="width:210px">
          <% if can?(:update, Order) || can?(:delete, Order) %>
            <col<%=manage_width(Order) %>>
          <% end %>
        </colgroup>
        <thead class="thead-default">
        <tr>
          <th class="text-center"><%= t(:enable,scope:[:activerecord,:attributes,:order]) %></th>
          <th><%= t(:title,scope:[:activerecord,:attributes,:order]) %></th>
          <th><%= t(:total_price,scope:[:activerecord,:attributes,:order]) %></th>
          <th class="text-right"><%= t(:created_at,scope:[:activerecord,:attributes,:order]) %></th>
          <% if can?(:update, Order) || can?(:delete, Order) %>
            <th class="text-center"><%= t(:manage) %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% unless @order_count.zero? %>
          <% @orders.each_with_index do |order,index| %>
            <tr>
              <td>
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="order_display<%=index %>" value="<%=order.id %>" <% if order.enable %> checked<% end %>>
                  <label class="custom-control-label" for="notice_display<%=index %>"><% if order.enable %> <%=t(:display) %><% else %><%=t(:hidden) %><% end %> </label>
                </div>
              </td>
              <td><%= link_to order.title,admin_order_path(order) %></td>
              <td></td>
              <td class="text-right"><%= I18n.l order.created_at.to_date, :format => :long %></td>
              <% if can?(:update, order) or can?(:delete, order) %>
                <td class="text-right">
                  <% if can? :update, order %>
                    <%= link_to edit_admin_order_path(order), :class => "btn btn-secondary" do %>
                      <%= t(:edit) %>
                    <% end %>
                  <% end %>
                  <% if can? :delete, order %>
                    <%= link_to admin_order_path(order), :method => :delete, :data => { :confirm => t(:delete_confirm) }, :class => "btn btn-danger" do %>
                      <%= t(:delete) %>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="5" class="text-center"><%= t(:no_data) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination justify-content-center">
        <%= paginate @orders %>
      </div>
      <%= link_to t(:add), new_admin_order_path, :class => "btn btn-primary" %>
    </article>

app/views/admin/orders/new.html.erb
<section id="new-order" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:new_order) %></h2>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', order: @order %>
    </div>
  </div>
</section>

app/views/admin/orders/show.html.erb
<section id="show-order" class="col-12">
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals => {:notice => notice, :alert => alert } %>
  </div>
  <div class="row">
    <div class="col-12">
      <article class="card">
        <h3 class="card-header"><%=@order.title %></h3>
        <div class="card-body">
          <dl>
            <dt><%= t(:title, scope: [:activerecord, :attributes, :product]) %></dt>
            <dd><% @order.products.each do |product| %>
                <%= product.title %><br>
              <% end %></dd>
            <dt><%= t(:created_at, scope: [:activerecord, :attributes, :order]) %></dt>
            <dd><%= I18n.l @order.created_at.to_date, :format => :long %></dd>
            <dt><%= t(:updated_at, scope: [:activerecord, :attributes, :order]) %></dt>
            <dd><%= I18n.l @order.updated_at.to_date, :format => :long %></dd>
          </dl>
        </div>
      </article>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      <%= link_to t(:link_list), admin_orders_path, class: 'btn btn-secondary' %>
    </div>
    <div class="col-12 col-xl-6 text-right">
      <%= link_to t(:edit), edit_admin_order_path(@order), class: 'btn btn-secondary' %>
      <%= link_to t(:delete), admin_order_path(@order), :method => :delete, :data => { :confirm => t(:delete_confirm) }, class: 'btn btn-danger' %>
    </div>
  </div>
</section>