config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'feed',:to=>'home#feed'

  get 'en', :to=> 'home#index',:defaults => { :locale => 'en'}
  get 'ko', :to=> 'home#index',:defaults => { :locale => 'ko'}
  get 'ch', :to=> 'home#index',:defaults => { :locale => 'zh-CN'}

  #faqs
  resources :faqs, only:[:index,:show]

  #contacts
  resources :contacts, only:[:index,:create, :show]
  get "/contacts/new", to: redirect("/contacts")

  #intro
  get 'intro', :to=>'intro#company', as: 'intro'
  get 'intro/service', :to=>'intro#service', as: 'intro_service'
  get 'intro/program', :to=>'intro#program', as: 'intro_program'

  resources :programs
  resources :accounts
  resources :accounts_products
  resources :accounts_product_categories
  resources :orders
  resources :reports
  resources :notices
  resources :users, :sitemap

  get "product_categories/:id",
      to: redirect(status: 301) { |params, _|
        "/orders?product_category=#{params[:id]}"
      },
      as: :product_category

  get "products/:id", to: redirect(status: 301) { |params, _req|
    "/orders?product=#{params[:id]}"
  }


  get 'install', :to=>'programs#install', as: 'program_install'

  devise_for :admins, :controllers => { :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}
  devise_for :users, :controllers => {:omniauth_callbacks=>'users/omniauth_callbacks', :sessions => "users/sessions",:registrations => "users/registrations",:passwords => "users/passwords"}, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  # 관리자
  namespace :admin do
    root to: 'home#index'

    resources :contacts
    resources :users
    resources :product_categories
    resources :products
    resources :orders
    resources :notices
    resources :faq_categories
    resources :faqs
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
  is_impressionable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content
  validates_presence_of :title
  has_one :notice_picture, dependent: :destroy
  accepts_nested_attributes_for :notice_picture, :allow_destroy => true
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < Admin::AdminController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @notice_count = Notice.count
    @notices = Notice.page(params[:page]).per(params[:per_page]).order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/complete
  def new
    @notice = Notice.new
    @notice.build_notice_content
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to [:admin, @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_create) }
        format.json { render :show, status: :created, location: @notice }
      else
        @notice.build_notice_content

        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to [:admin, @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_update) }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to admin_notices_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:title, :popup, :enable, notice_content_attributes: [:content])
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  #impressionist :actions => [:show]
  before_action :set_notice, only: [:show]

  # GET /notices
  # GET /notices.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    condition = {  enable: true }

    @notice_count = Notice.where(condition).count
    @notices = Notice.where(condition).page(params[:page]).per(params[:per_page]).order('id desc')
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @comment  = Comment.build_from(@notice, current_user, "")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end
end

app/views/admin/notices/_form.html.erb
<%= form_with(model: [:admin, notice], local: true) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <h2><%= pluralize(notice.errors.count, "개의 문제") %>로 진행할 수 없습니다.</h2>
      <ul>
        <% notice.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, :class => 'form-control', :required => 'required' %>
      </div>
      <%= form.fields_for :notice_content do |c| %>
        <div class="form-group">
          <%= c.label :content %>
          <%= c.text_area :content, :id => "sl_content", :class => 'form-control' %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :enable %>
      <%= form.check_box :enable %>
    </div>
  </div>
  <div class="form-group actions">
    <%= form.submit :class => "btn btn-primary btn-block btn-lg" %>
  </div>
<% end %>

app/views/admin/notices/_nav.html.erb
<%
    a_class = 'nav-link'
    b_class = 'nav-link'
    c_class = 'nav-link'
    d_class = 'nav-link'

    if params[:controller] == 'admin/notices'
      a_class += ' active'
    end

    if params[:controller] == 'admin/contacts'
      b_class += ' active'
    end

    if params[:controller] == 'admin/faqs'
      c_class += ' active'
    end

    if params[:controller] == 'admin/faq_categories'
      d_class += ' active'
    end

  %>
  <div class="col-12">
    <nav class="sub-nav">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to t(:notice, scope: [:activerecord, :models]), admin_notices_path, { :class => a_class } %></li>
        <li class="nav-item"><%= link_to t(:contact, scope: [:activerecord, :models]), admin_contacts_path, { :class => b_class } %></li>
        <li class="nav-item"><%= link_to t(:faq, scope: [:activerecord, :models]), admin_faqs_path, { :class => c_class } %></li>
        <li class="nav-item"><%= link_to t(:faq_category, scope: [:activerecord, :models]), admin_faq_categories_path, { :class => d_class } %></li>
      </ul>
    </nav>
  </div>

app/views/admin/notices/edit.html.erb
<section id="edit-notice" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:edit_notice) %></h2>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', notice: @notice %>
    </div>
  </div>
</section>

app/views/admin/notices/index.html.erb
<div class="col-12">
  <h2 class="float-start d-none d-lg-block"><%= t(:notice,scope: [:activerecord,:models]) %></h2>
  <div class="float-end">
    <p class="summary text-end">
          <span id="list_count" style="display:none"><%=@notice_count %></span>
          <%=raw t(:there_are_n_notices,count: @notice_count) %>
        </p>
      </div>
    </div>
    <article class="col-12">
      <table id="prepare_list" class="table table-striped table-hover">
        <colgroup>
          <col style="width:120px">
          <col>
          <col style="width:200px">
          <% if can?(:update, Notice) || can?(:delete, Notice) %>
            <col<%=manage_width(Notice) %>>
          <% end %>
        </colgroup>
        <thead class="thead-default">
        <tr>
          <th class="text-center"><%= t(:enable,scope:[:activerecord,:attributes,:notice]) %></th>
          <th><%= t(:title,scope:[:activerecord,:attributes,:notice]) %></th>
          <th class="text-right"><%= t(:created_at,scope:[:activerecord,:attributes,:notice]) %></th>
          <% if can?(:update, Notice) || can?(:delete, Notice) %>
            <th class="text-center"><%= t(:manage) %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% unless @notice_count.zero? %>
          <% @notices.each_with_index do |notice,index| %>
            <tr>
              <td>
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="notice_display<%=index %>" value="<%=notice.id %>" <% if notice.enable %> checked<% end %>>
                  <label class="custom-control-label" for="notice_display<%=index %>"><% if notice.enable %> <%=t(:display) %><% else %><%=t(:hidden) %><% end %> </label>
                </div>
              </td>
              <td><%= link_to notice.title,admin_notice_path(notice) %></td>
              <td class="text-right"><%= notice.impressionist_count(:filter => :ip_address) %></td>
              <td class="text-right"><%= I18n.l notice.created_at.to_date, :format => :long %></td>
              <% if can?(:update, notice) or can?(:delete, notice) %>
                <td class="text-right">
                  <% if can? :update, notice %>
                    <%= link_to edit_admin_notice_path(notice), :class => "btn btn-secondary" do %>
                      <%= t(:edit) %>
                    <% end %>
                  <% end %>
                  <% if can? :delete, notice %>
                    <%= link_to admin_notice_path(notice), :method => :delete, :data => { :confirm => t(:delete_confirm) }, :class => "btn btn-danger" do %>
                      <%= t(:delete) %>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="4" class="text-center"><%= t(:no_data) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination justify-content-center">
        <%= paginate @notices %>
      </div>
      <%= link_to t(:add), new_admin_notice_path, :class => "btn btn-primary" %>
    </article>

app/views/admin/notices/new.html.erb
<section id="new-notice" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:new_notice) %></h2>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', notice: @notice %>
    </div>
  </div>
</section>

app/views/admin/notices/show.html.erb
<section id="show-notice" class="col-12">
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals => {:notice => notice, :alert => alert } %>
  </div>
  <div class="row">
    <div class="col-12">
      <article class="card">
        <h3 class="card-header"><%=@notice.title %></h3>
        <div class="card-body">
          <dl>
            <dt><%= t(:created_at, scope: [:activerecord, :attributes, :product]) %></dt>
            <dd><%= I18n.l @notice.created_at.to_date, :format => :long %></dd>
            <dt><%= t(:updated_at, scope: [:activerecord, :attributes, :product]) %></dt>
            <dd><%= I18n.l @notice.updated_at.to_date, :format => :long %></dd>
          </dl>
        </div>
      </article>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      <%= link_to t(:link_list), admin_notices_path, class: 'btn btn-secondary' %>
    </div>
    <div class="col-12 col-xl-6 text-right">
      <%= link_to t(:edit), edit_admin_notice_path(@notice), class: 'btn btn-secondary' %>
      <%= link_to t(:delete), admin_notice_path(@notice), :method => :delete, :data => { :confirm => t(:delete_confirm) }, class: 'btn btn-danger' %>
    </div>
  </div>
</section>